title: Peace Fixation
baseURL: http://localhost:8080
canonicalURL: https://peacefixation.github.io
contentDir: content
outputDir: public
templateDir: templates
themesDir: themes
theme: default

server:
  host: localhost
  port: 8080

sitemap: true

defaults:
  page:
    template: page.html
  list:
    template: list.html
    cardTemplate: item.html
    sortBy: date
    sortOrder: desc
