title: Peace Fixation
baseURL: http://localhost:8080
canonicalURL: https://peacefixation.github.io
contentDir: content
outputDir: public
staticDir: static
templateDir: templates
themesDir: themes
theme: default

server:
  host: localhost
  port: 8080

sitemap: true

staticJS:
  - js/embed-collapsible.js
  - js/slideshow.js

defaults:
  page:
    template: item.html
  list:
    template: list.html
    cardTemplate: card.html
    sortBy: date
    sortOrder: desc

tags:
  enabled: true
  style: cloud
